#!/bin/sh

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/bin/fbink
DEVICE=$(cat /opt/device)

if [ "${DEVICE}" == "n705" ] || [ "${DEVICE}" == "n905b" ] || [ "${DEVICE}" == "n905c" ]; then
	ROW=30
elif [ "${DEVICE}" == "n613" ]; then
	ROW=37
else
	ROW=30
fi

/opt/bin/fbink/fbink -k -f -h -q
/opt/bin/fbink/fbink -k -f -h -q
/opt/bin/fbink/fbink -t regular=/opt/fonts/inter-b.ttf,size=20 "Restoring" -m -M -h -q

while true; do
	/opt/bin/fbink/fbink "██ ████████" -y ${ROW} -m -q
	sleep 1
	/opt/bin/fbink/fbink "██ ██ █████" -y ${ROW} -m -q
	sleep 1
	/opt/bin/fbink/fbink "██ ██ ██ ██" -y ${ROW} -m -q
	sleep 1
	/opt/bin/fbink/fbink "█████ ██ ██" -y ${ROW} -m -q
	sleep 1
	/opt/bin/fbink/fbink "████████ ██" -y ${ROW} -m -q
	sleep 1
	/opt/bin/fbink/fbink "███████████" -y ${ROW} -m -q
	sleep 1;
done
