#!/bin/sh

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/bin/fbink

DEVICE=$(cat /opt/device)

if [ "${DEVICE}" == "n705" ] || [ "${DEVICE}" == "n905b" ] || [ "${DEVICE}" == "n905c" ] || [ "${DEVICE}" == "kt" ]; then
	ROW=30
elif [ "${DEVICE}" == "n613" ] || [ "${DEVICE}" == "n236" ] || [ "${DEVICE}" == "n306" ]; then
	ROW=37
elif [ "${DEVICE}" == "n437" ]; then
	ROW=35
fi

/opt/bin/fbink/fbink -k -f -h -q -w
/opt/bin/fbink/fbink -k -f -h -q -w
/opt/bin/fbink/fbink -t regular=/opt/fonts/inter-b.ttf,size=20 "Updating" -m -M -h -q -w

while true; do
	/opt/bin/fbink/fbink "██ ████████" -y ${ROW} -m -q
	sleep 1
	/opt/bin/fbink/fbink "██ ██ █████" -y ${ROW} -m -q
	sleep 1
	/opt/bin/fbink/fbink "██ ██ ██ ██" -y ${ROW} -m -q
	sleep 1
	/opt/bin/fbink/fbink "█████ ██ ██" -y ${ROW} -m -q
	sleep 1
	/opt/bin/fbink/fbink "████████ ██" -y ${ROW} -m -q
	sleep 1
	/opt/bin/fbink/fbink "███████████" -y ${ROW} -m -q
	sleep 1;
done
